# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastai_journey',
                'doc_host': 'https://fredguth.github.io',
                'git_url': 'https://github.com/fredguth/fastai_journey',
                'lib_path': 'fastai_journey'},
  'syms': {'fastai_journey.core': {'fastai_journey.core.foo': ('core.html#foo', 'fastai_journey/core.py')}}}